# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
date_format: "ordinal"
title: GongYangbo
# subtitle: "你给我的地图画好了快乐的路。"
description: "公杨博的个人博客"
keywords: gongyangbo
favicon: /g.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Gong YangBo
github_username: gongyangbo
location: ChengDu, China
email: gongyangbo@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categories

  # -
  #   href: /wiki/
  #   label: 维基

  -
    href: /aboutme/
    label: About-Me

  # -
  #   href: /links/
  #   label: 链接

  # -
  #   href: /about/
  #   label: Somethings

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: gongyangbo/gongyangbo.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment
comments_provider: gitment

gitment:
    owner: gongyangbo
    repo: blog-comments
    oauth:
        client_id: d2e1cbbd298958076462
        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
